export default {
    name: "Arepsalin",
      "coptic": [
        "`Ari'alin `evy`[email&#160;protected] `e`hryi `ejwn ouoh [email&#160;protected] aftwnf afkwrf `m`vmou af][email&#160;protected] hwc `erof `arihou`o [acf.\nBws `mpirwmi `[email&#160;protected] ouoh jwlh `mpiberi eu`[email&#160;protected] ouoh `eqwnt `emega`[email&#160;protected] hwc `erof `arihou`o [acf.",
        "+ Genoc `nNi`,[email&#160;protected] ni`precbuteroc ke [email&#160;protected] ma`wou `m`P[oic je [email&#160;protected] hwc `erof `arihou`o [acf. \n+ Deute haron `w pisomt `n`[email&#160;protected] `eta Pi`,rictoc Pennou] `[email&#160;protected] afnahmou `ebol ha [email&#160;protected] hwc `erof `arihou`o [acf.",
        "E;be Peknou] [email&#160;protected] `Vref] `[email&#160;protected] `amou saron `[email&#160;protected] hwc `erof `arihou`o [acf. \nZylwte `[email&#160;protected] ecperac ke `prw`i ke mecym `[email&#160;protected] ma`wou `n`tjom `n}`[email&#160;protected] hwc `erof `arihou`o [acf. ",
        "+ Yppe gar ic [email&#160;protected] hi tenmy] `w [email&#160;protected] lali qen ou`cmy `n;[email&#160;protected] hwc `erof `arihou`o [acf. \n+ :wou] ]nou kata ,in [email&#160;protected] caji nem ni`[email&#160;protected] `cmou `e`P[oic nef`hbyou`i [email&#160;protected] hwc `erof `arihou`o [acf. ",
        "Ic nivyou`i cecaji `m`p`[email&#160;protected] `m`Vnou] sa `eqoun `[email&#160;protected] `w niaggeloc `etaf`[email&#160;protected] hwc `erof `arihou`o [acf.\nKe nun dunamic tou [email&#160;protected] `cmou `epefran tou [email&#160;protected] piry nem piioh nem [email&#160;protected] hwc `erof `arihou`o [acf. ",
        "+ Loipon nimou`nhwou nem niiw]@ euvymica te Penrefcw]@ je `n;of pe `Vnou] `nte nenio]@ hwc `erof `arihou`o [acf. \n+ Ma`wou `m`P[oic `w ni[ypi [email&#160;protected] ni;you nem ninifi nem ni`[email&#160;protected] pijaf nem pi`,rwm nem [email&#160;protected] hwc `erof `arihou`o [acf. ",
        "Nuktec ke `ymererw [email&#160;protected] vwc ke `ckotoc ke ac`[email&#160;protected] je doxa ci Vilan`;[email&#160;protected] hwc `erof `arihou`o [acf. \nXula ke panta ta vu`[email&#160;protected] en ty gy ke panta ta [email&#160;protected] hi nimwou nem nitwou nem `[email&#160;protected] hwc `erof `arihou`o [acf. ",
        "+ Ouoh on `cmou `nat,[email&#160;protected] `e`P[oic `Pouro `nte [email&#160;protected] ni`amaiou nem [email&#160;protected] hwc `erof `arihou`o [acf.\n+ Pairy] `anon tennau `[email&#160;protected] marenjoc nem nai wn [email&#160;protected] `cmou `e`P[oic nihala] [email&#160;protected] hwc `erof `arihou`o [acf. ",
        "Rw `nnipa,ny nem ni,[email&#160;protected] ke `ktynwn nem ni;[email&#160;protected] `cmou `e`P[oic twn [email&#160;protected] hwc `erof `arihou`o [acf. \n`Cmou `e`P[oic kata `[email&#160;protected] `erof ke ou my [email&#160;protected] `w nisyri `nte [email&#160;protected] hwc `erof `arihou`o [acf. ",
        "+ Timy ke doxa `w [email&#160;protected] `ini nahraf qen ou`cmy `n;[email&#160;protected] niouyb `nte [email&#160;protected] hwc `erof `arihou`o [acf. \n+ `Upyretwn `m`Vnou] `[email&#160;protected] nem ni'u,y `nte ni`;[email&#160;protected] nyet;ebiyout `[email&#160;protected] hwc `erof `arihou`o [acf. ",
        "`Vnou] Panou] `[email&#160;protected] Petenrefcw] ek ton `[email&#160;protected] Cedrak Micak [email&#160;protected] hwc `erof `arihou`o [acf. \n&lt;wlem qen ounis] `n`[email&#160;protected] `w nyetercebec;e `m`P[[email&#160;protected] nem nivucic tyrou `[email&#160;protected] hwc `erof `arihou`o [acf. ",
        "+ &quot;u,oc ke `[email&#160;protected] moi nan tyren ,wric `;[email&#160;protected] e;renjw qen ou`[email&#160;protected] hwc `erof `arihou`o [acf. \n+ `Wcautwc pekbwk pi`ptw,[email&#160;protected] Carkic `aritf efoi `neno,[email&#160;protected] `ecaji nem nai hwc meto,[email&#160;protected] hwc `erof `arihou`o [acf."
      ],
      "english": [
        "O sing unto Him who was crucified, buried and resurrected, who trampled and abolished death, praise Him and exalt Him above all.\nTake off the old man, and put on the new and superior one, come closer to greatness of mercy, praise Him and exalt Him above all. ",
        "+ All you Christian people, the priests and the deacons, glorify the Lord for He is worthy, praise Him and exalt Him above all. \n+ Come to us O three children, whom Christ our God has lifted, and from the Devil has delivered, praise Him and exalt Him above all. ",
        "For the sake of your God the Messiah, the Giver of all good things, come unto us O Hananiah, praise Him and exalt Him above all. \nO Azariah the zealot, morning and noon and the evening, glorify the power of the Trinity, praise Him and exalt Him above all. ",
        "+ Behold Emmanuel [our Lord], is now in our midst O Mishael, proclaim with the voice of joy, praise Him and exalt Him above all. \n+ Gather now and persevere, and proclaim with the priests, bless the Lord all His works, praise Him and exalt Him above all. ",
        "The heavens declare the glory, of God until this day, O you angels whom He has made, praise Him and exalt Him above all. \nNow all you powers of the Lord, bless His honored name, O sun and moon and all the stars, praise Him and exalt Him above all. ",
        "+ And also you rain and dew, sing praises unto our Savior, for He is the God of our fathers, praise Him and exalt Him above all.\n+ Glorify the Lord O clouds and winds, together with the souls and the spirits, O you cold and fire and heat, praise Him and exalt Him above all.",
        "You also nights and days, light and darkness and lightning, glorify the Lover of Mankind, praise Him and exalt Him above all. \nYou trees and all that springs on the earth, and all that moves in the sea, mountains and the forests, praise Him and exalt Him above all. ",
        "+ Praise without ceasing, the Lord the King of the kings, O you rivers and seas, praise Him and exalt Him above all. \n+ And we also seeing them, let us say with all these things, bless the Lord all you birds, praise Him and exalt Him above all. ",
        "O snow and ice, cattle and wild beasts, bless the Lord of lords, praise Him and exalt Him above all. \nBless the Lord as befits Him, and not like the heretics, all you sons of men, praise Him and exalt Him above all.",
        "+ O Israel offer before Him, honor and glory in a joyful voice, all you priests of Emmanuel, praise Him and exalt Him above all. \n+ You servants of the true God, the souls of the righteous, and the humble and the charitable, praise Him and exalt Him above all. ",
        "God my God is the One, who saved you from danger, O Sedrach Misach and Abednago, praise Him and exalt Him above all.\nHurry with great haste, O you righteous of the Lord, and all the creatures He has made, praise Him and exalt Him above all. ",
        "+ Coolness and repose without ceasing, grant unto all of us, that we may joyfully proclaim, praise Him and exalt Him above all. \n+ And also Your poor servant Sarkis, make him without condemnation, that he may join all those and say, praise Him and exalt Him above all. "
      ],
      "copticEnglish": [
        "Aripsalin efe-etav ashf, e-ehri egon owoh avkosf, aftonf afkorf emef-mo afti shoshf, hos erof areh ho-oo chasf.",
        "Genos enikh-resteyanos, ni-epres-veteros ke zeia-konos, ma-o-oo emip-shois je ohi-kanos, hos erof areh ho-oo chasf.\nZevte haron o-pi-shomt en-alo, eta Pekhrestos pennouti olo, af-nahmo evol hapi-zeiav-lo, hos erof areh ho-oo chasf.",
        "Ethve peknouti Maseias, ef-refti enev-erge-seias, a-mo sharon Ana-neias, hos erof areh ho-oo chasf.\nZelote Azareias, esperas ke epro-e ke miss-mev-reias, ma-o-oo enet-gom in-Tit-reias, hos erof areh ho-oo chasf.",
        "Eppe ghar yes Emmanoueel, he ten-me-ti o Mesaeel, lali khen o-esme en-theleel, hos erof areh ho-oo chasf.\nTho-ooti tino kate shin teroo, saji nemni-epres-ve-tero, esmo Epshois nef-ehve-owee teroo, hos erof areh ho-oo chasf.",
        "Yes nefee-owe se-saji emip-o-oo, Emif-nouti sha ekhon em-fo-oo, o ni-angelos etaf-egfo-oo, hos erof areh ho-oo chasf.\nKe nin zenamis too Kereie, esmo epif-ran to ti-meio, piree nem peyoh nem ni-seio, hos erof areh ho-oo chasf.",
        "Leboon ni-monho-oo nem nei-yoti, ev-fi-misa te penref-souti, je enthof pe Efnouti ente nen-yoti, hos erof areh ho-oo chasf.\nMa-oo Emip-shois o ni-etshepi evma, ni-theio nem ni-nifi nem ni-epnev-ma, pi-gaf nem pek-rom nem pi-kavma, hos erof areh ho-oo chasf.",
        "Nektes ke emre-rope, fos ke es-kotos ke asit-rape, je zoxa see filan-ethrope, hos erof areh ho-oo chasf.\nExela ke panta ta fi-omina, en ti-ge ke panta ta ki-no-mina, he ni-mo-oo nem ni-to-oo nem ezri-mona, hos erof areh ho-oo chasf.",
        "Owoh on esmo an-atkaro-oo, Epshois ep-Oroo ente ni-ero-oo, ni-a-maio nem ni-aro-oo, hos erof areh ho-oo chasf.\nPai-reti anon ten-nav ero-o, maren-gos nem nai on teroo, esmo Epshois ni-halati teroo, hos erof areh ho-oo chasf.",
        "Ro enni-pakhni nem ni-sheion, ke ekti-non nem ni-thereion, esmo Epshois ton ke-reion, hos erof areh ho-oo chasf.\nEsmo Epshois kata ef-tomi, erof ke o-me para-nomee, o ni-shere ente ni-roumi, hos erof areh ho-oo chasf.",
        "Ti-me ke zoxa o pis-rael, eni nah-raf khen o-esmi en-theleel, ni-oweb ente Emmanoueel, hos erof areh ho-oo chasf.\nEe-per-ton Emif-nouti emme, nem ni-epsi-shi ente ni-ethme, ni-et-thevio enref-me, hos erof areh ho-oo chasf.",
        "Efnouti panouti ego, peten-ref-souti ekton ago, Cedrak Misak Abde-nagi, hos erof areh ho-oo chasf.\nKolem khen oo-nishti e-nesh-rois, o ni-et-er-sebeste Emipshois, nem ni-fee-sis teroo etaf-ais, hos erof areh ho-oo chasf.",
        "Epsi-khos ke ana pav-sees, moi nan ti-ren khores ethrav-sees, ethren-go khen oo-apolo-lav-sees, hos erof areh ho-oo chasf.\nO-savtos pek-vok pi-epto-khos, Sarkis aritf efoi ennen-khos, e-saji nem nai hos meto-khos, hos erof areh ho-oo chasf."
      ],
      "arabic": [
        "إبصالية واطس للثلاثة فتية القديسين - رومية",
        "رتلوا للذي صُلب عنا، وقُبر وقام، وأبطل الموت وأهانه، سبحوه وزيدوه علواً.\nإخلعوا الإنسان العتيق، وألبسوا الجديد الفاخر، وإقتربوا إلى عِظَم الرحمة، سبحوه وزيدوه علواً.",
        "+ يا جنس المسيحيين، القسوس والشمامسة، أعطوا مجداً للرب لأنه مستوجب، سبحوه وزيدوه علواً.\n+ هَلُمَّ إلينا أيها الثلاثة فتية، الذين رفعهم المسيح إلهنا، وأنقذهم من إبليس، سبحوه وزيدوه علواً.",
        "من أجل إلهك ماسيا، المانح الإحسان، هَلُمَّ إلينا يا حنانيا، سبحوه وزيدوه علواً.\nيا عزاريا الغيور، عشية وبكرة والظهيرة، أعط مجداً لقوة الثالوث، سبّحه وزده علواً. ",
        "+ فها هوذا عمانوئيل، في وسطنا يا ميصائيل، تكلم بصوت التهليل، سبّحه وزده علواً.\n+ إجتمعوا وثابروا جميعاً، تكلموا مع القسوس، وسبحي الرب يا جميع أعماله، سبحوه وزيدوه علواً.",
        "ها السموات تنطق بمجد الله، إلى هذا اليوم، يا أيها الملائكة الذين أنشأهم، سبحوه وزيدوه علواً.\nوالآن يا قوات الرب، باركوا إسمه الكريم، أيتها الشمس والقمر والنجوم، سبحيه وزيديه علواً.",
        "+ وأيضاً أيتها الأمطار والأنداء، إمدحي مخلصنا، لأنه هو إله آبائنا، سبحيه وزيديه علواً. \n+ أعطي مجداً أيتها السحب معاً، والأهوية والنفوس والأرواح، والبرد والنار والحرارة، سبحيه وزيده علوا.",
        "أيتها الليالي والأيام أيضاً، والنور والظلمة والبروق، قائلة المجد لك يا محب البشر، سبحوه وزيدوه علواً.\nأيتها الأشجار وجميع ما ينبُت، في الأرض وكل ما يتحرك، في المياه والجبال والغياض، سبحوه وزيدوه علواً.",
        "+ وأيضاً سبحي بغير فتور، الرب ملك الملوك، أيتها البحار والأنهار، سبحيه وزيديه علواً.\n+ هكذا نحن إذ ننظر إليهم، فلنقل مع هذه الموجودات جميعها، باركي الرب يا جميع الطيور، سبحيه وزيده علواً.",
        "أيها الجليد والثلج، والبهائم والوحوش، باركي رب الأرباب، سبحيه وزيديه علواً. \nسبحوا الرب كما يليق به، وليس كالمخالفين، يا أبناء البشر، سبحوه وزيدوه علواً.",
        "+ مجداً وإكراماً قدم أمامه، يا إسرائيل بصوت التهليل، يا كهنة عمانوئيل، سبحوه وزيدوه علواً.\n+ يا خدام الله الحقيقي، وأنفس الأبرار، المتواضعين المحبين، سبحوه وزيدوه علواً.",
        "الله إلهي أنا، هو مخلصكم من الخطر، يا سدراك وميساك وأبدناغو، سبحوه وزيدوه علوا.\nأسرعوا بحرص عظيم، يا أتقياء الرب، وكل الطبائع التي صنعها، سبحوه وزيدوه علواً.",
        "+ برودة ونياحاً أعطنا، كلنا بغير إنقطاع، لنقول بتمتُع، سبحوه وزيدوه علواً. \n+ كذلك عبدك المسكين سركيس، إجعله بغير دينونة، ليقول مع هؤلاء كشريك، سبحوه وزيدوه علواً. "
      ]
    }
  