export default {
    name: "Fourth Hoos",
      "coptic": [
        "Pihwc `mMah`ftoou",
        "(&quot;almoc =r=m=y) ",
        "+ `Cmou `e`P[oic `ebol qen nivyou`i allylouia. `Cmou `erof qen nyet[oci. ",
        "`Cmou `erof nefaggeloc tyrou allylouia. `Cmou `erof nefdunamic tyrou. ",
        "+ `Cmou `erof piry nem piioh allylouia. `Cmou `erof niciou tyrou `nte piouwini. ",
        "`Cmou `erof nivyou`i `nte nivyou`i allylouia. Nem nikemwou etca `pswi `nnivyou`i. ",
        "+ Marou`cmou tyrou `e`vran `m`P[oic allylouia. Je `n;of afjoc ouoh auswpi. ",
        "`N;of afhonhen ouoh aucwnt allylouia. Aftahw`o `eratou sa `eneh nem sa `eneh `nte pi`eneh. ",
        "+ Af,w `nouhwn ouoh `nnefcini allylouia. `Cmou `e`P[oic `ebol qen `pkahi. ",
        "Ni`drakwn nem ninoun tyrou allylouia. Ou`,rwm oual ou,iwn ou`,ructalloc ou`pneuma `ncara;you nyet`iri `mpefcaji.",
        "+ Nitwou et[oci nem nikalamvwou tyrou allylouia. Ni`ssyn `mfaioutah nem nisencifi tyrou.",
        "Ni;yrion nem nitebnwou`i tyrou allylouia. Ni[atfi nem nihala] etoi `ntenh.",
        "+ Niourwou `nte `pkahi nem nilaoc tyrou allylouia. Niar,wn nem niref]hap tyrou `nte `pkahi. ",
        "Hanqelsiri nem hanpar;enoc allylouia. Hanqelloi nem han`alwou`i. ",
        "+ Marou`cmou tyrou `e`vran `m`P[oic allylouia. Je af[ici `nje pefran `mmauatf.",
        "Pefouwnh `ebol sop hijen `pkahi nem `n`hryi qen `tve allylouia. `Fna[ici `m`ptap `nte peflaoc. ",
        "+ Ou`cmou `nte nye;ouab tyrou `ntaf allylouia. Nensyri `[email&#160;protected] pilaoc et qent `erof. ",
        "(&quot;almoc =r=m=;) ",
        "[email&#160;protected] [email&#160;protected] allylouia. ",
        "Jw `m`P[oic qen oujw `mberi allylouia. Je `are pef`cmou qen `tekklycia `nte nye;ouab. ",
        "+ Marefounof `nje Picrayl `ejen vy`etaf;amiof allylouia. Nensyri `nCiwn marou;elyl `ejen Pououro. ",
        "Marou`cmou `epefran e;ouab qen ou,oroc allylouia. Qen oukemkem nem ou'altyrion marouer'alin `erof. ",
        "+ Je `P[oic na]ma] `ejen peflaoc allylouia. `Fna[ici `nniremraus qen ououjai. ",
        "Eu`esousou `mmwou `nje nye;ouab qen ou`wou allylouia. Eu`e;elyl `mmwou hijen noumanenkot. ",
        "+ Ni[ici `nte `Vnou] et,y qen tou`sbwbi allylouia. Hancyfi `nro`cnau et,y qen noujij.",
        "`E`pjin`iri `nou[i`m`psis qen nie;noc allylouia. Nem hancohi qen nilaoc. ",
        "+ `E`pjincwnh `nhanourwou qen hanpedyc allylouia. Nem nyettaiyout `ntwou qen hanpedyc `njij `mbenipi. ",
        "`E`pjin`iri `nqytou `nouhap ef`cqyout allylouia. Pai`wou vai afsop qen nye;ouab tyrou `ntaf. ",
        "(&quot;almoc =r=n)",
        "+ [email&#160;protected] [email&#160;protected] allylouia. ",
        "+ `Cmou `e`Vnou] qen nye;ouab tyrou `ntaf allylouia. ",
        "`Cmou `erof qen pitajro `nte tefjom allylouia. ",
        "+ `Cmou `erof `e`hryi hijen tefmetjwri allylouia.",
        "`Cmou `erof kata `p`asai `nte tefmetnis] allylouia.",
        "+ `Cmou `erof qen ou`cmy `ncalpiggoc allylouia.",
        "`Cmou `erof qen ou'altyrion nem ouku;ara allylouia.",
        "+ `Cmou `erof qen hankemkem nem han,oroc allylouia. ",
        "`Cmou `erof qen hankap nem ouorganon allylouia. ",
        "+ `Cmou `erof qen hankumbalon `enece tou`cmy allylouia. ",
        "`Cmou `erof qen hankumbalon `nte oueslylou`i allylouia. ",
        "+ Nifi niben marou`cmou tyrou `e`vran `m`P[oic Pennou] allylouia. ",
        "Doxa Patri ke `Uiw ke `Agiw `Pneumati allylouia.",
        "+ Ke nun ke `a`i ke ic touc `e`wnac twn `e`wnwn `amyn allylouia. ",
        "[email&#160;protected] =a=l. Doxa ci `o :eoc `ymwn allylouia. ",
        "+ [email&#160;protected] =a=l. Pi`wou va Pennou] pe allylouia."
      ],
      "english": [
        "(Psalm 148) ",
        "+ Praise the Lord from the heavens Alleluia. Praise Him in the heights. ",
        "Praise Him all His angels Alleluia. Praise Him all His hosts. ",
        "+ Praise Him sun and moon Alleluia. Praise Him all you stars of light. ",
        "Praise Him you heavens of heavens Alleluia. And you waters above the heavens. ",
        "+ Let them praise the name of the Lord Alleluia. For He commanded and they were created. ",
        "He has ordered and they were created Alleluia. He has established them forever and ever. ",
        "+ He has made a decree which shall not pass away Alleluia. Praise the Lord from the earth. ",
        "You great sea creatures and all the depths Alleluia. Fire and hail, snow and clouds, stormy wind fulfilling His word. ",
        "+ Mountains and all hills Alleluia. Fruitful trees and all cedars. ",
        "Beasts and all cattle Alleluia. Creeping things and flying birds. ",
        "+ Kings of the earth and all people Alleluia. Princes and all judges of the earth. ",
        "Both young men and maidens Alleluia. Old men and children. ",
        "+ Let them praise the name of the Lord Alleluia. For His name alone is exalted. ",
        "His glory is above the earth and heaven Alleluia. And He has exalted the horn of His people. ",
        "+ The praise of all His saints Alleluia. The children of Israel, a people near unto Him. ",
        "(Psalm 149) ",
        "Alleluia, Alleluia, Alleluia.",
        "Sing to the Lord a new song Alleluia. And His praise in the congregation of the saints. ",
        "+ Let Israel rejoice in his Maker Alleluia. Let the children of Zion be joyful in their King. ",
        "Let them praise His name in a chorus Alleluia. Let them sing praises unto Him with timbrel and harp. ",
        "+ For the Lord takes pleasure in His people Alleluia. He will raise the meek with salvation. ",
        "Let the saints be joyful in glory Alleluia. Let them sing aloud upon their beds. ",
        "+ Let the high praises of God be in their mouth Alleluia. And a two edged sword in their hands. ",
        "To execute vengeance on the nations Alleluia. And punishments on the people. ",
        "+ To bind their kings with chains Alleluia. And their nobles with fetters of iron. ",
        "To execute on them the written judgment Alleluia. This honor have all His saints. ",
        "(Psalm 150)",
        "+ Alleluia, Alleluia, Alleluia. ",
        "+ Praise God in all His saints Alleluia. ",
        "Praise Him in the firmament of His power Alleluia. ",
        "+ Praise Him for His mighty acts Alleluia. ",
        "Praise Him according to the multitudes of His greatness Alleluia.",
        "+ Praise Him with the sound of the trumpet Alleluia. ",
        "Praise Him with psaltery and harp Alleluia. ",
        "+ Praise Him with timbrel and chorus Alleluia.",
        "Praise Him with strings and organs Alleluia.",
        "+ Praise Him with pleasant sounding cymbals Alleluia.",
        "Praise Him upon the cymbals of joy Alleluia. ",
        "+ Let every thing that has breath praise the name of the Lord our God Alleluia. ",
        "Glory be to the Father and the Son and the Holy Spirit Alleluia. ",
        "+ Now and forever and unto the age of all ages Amen Alleluia. ",
        "Alleluia, Alleluia. Glory to You, O our God Alleluia.",
        "+ Alleluia, Alleluia. Glory be to our God Alleluia. "
      ],
      "copticEnglish": [
        "Esmo Epshois evol khen nifi-owi, alleloia. Esmo erof khen ni-etitshosi.",
        "Esmo erof nef-angelos tiro, alleluia. Esmo erof nef-zinamis tiro.",
        "Esmo erof piri nem peyoh, alleluia. Esmo erof nisayo tiro ente pi-ou-oyni.",
        "Esmo erof nifi-owi ente nifi-owi, alleluia. Nem ni-kemo-ou etsa epshoy ennifi-owi.",
        "Marou-esmo tiro e-ephran Emipshois, alleluia. Je enthof afgos owoh av-showpi.",
        "Enthof afhon-hen owoh avsont, alleluia. Afta-hoo eratou sha eneh ente pi-eneh.",
        "Afko en-ou-hon owoh ennef-sini, alleluia. Esmo Epshois evol khen epkahi.",
        "Ni-ezrakown nem ni-noun tiro, alleluia. Ou-ekrowm ou-al ou-sheion, ou-ekris-tallos, ou-epnevman-sara-theio, ni-et-ere empef-sagi.",
        "Ni-tow-ou etit-shosi, nem nikalamfow-ou tiro, alleluia. Neiesh-shin emfai-otah nem nishen-sifi tiro.",
        "Ni-therion nem ni-tev-noowi tiro, alleluia. Ni-echatifw nem ni-halati et-oi entenh.",
        "Ni-oro-ou ente epkahi nem ni-laos tiro, alleluia. Ni-arkhown nem ni-reftihap tiro ente epkahi.",
        "Han-khel-shiri nem han-parthinos, alleluia. Han-khelloi nem han-aloowi.",
        "Marou-esmo tiro e-ephran Emipshois, alleluia. Je afit-shisi enje pefran emma-vatf.",
        "Pef-ou-ownh evol shop hijen epkahi nem en-ehri khen etva, alleluia. Efna-chisi em-ep-tap ente pef-laos.",
        "Ou-esmo ente ni-ethowab tiro entaf, alleluia. Nen-shiri empis-rael, pi-laos etkhent erof.",
        "Alleluia, Alleluia, Alleluia.",
        "Go emip-shois khen ou-go emviri, alleluia. Je a-ri pef-esmo khen ti-ekliseia ente ni-ethowab.",
        "Maref-onof enje pis-rael eijen fi-e-taf-thamiof, alleluia. Nen-shiri en-Seion marou-thelil eijen epouro.",
        "Marou-esmo epefran ethowab khen o-khoros, alleluia. Khen o-kem-kem nem opsal-tereion marou-erpsalin erof.",
        "Je Epshois nati mati ejen pef-laos, alleluia. Ef-na-chisi enni-rem-ravsh khen ou-ougai.",
        "Ev-e-shou-shou emmow-ou enje-ni-ethowab khen ou-ow-ou, alleluia. Evethelil emmow-ou, hijen noma-nenkot.",
        "Nit-shisi ente Efnouti, etki khen tow-esh-vovi, alleluia. Han-sify enro-esnaf etki khen noujig.",
        "Ei-epjen-eiri enou-etshi emipshish khen ni-ethnos, alleluia. Nem han-sohi khen ni-laos.",
        "Ei-epjen-sowonh enhan-owroou khen han-pezis, alleluia. Nem ni-etta-yout entow-ou khen han pezis enjig em-venipi.",
        "Ei-epjin-eiri enkhitou en-ouhap e-fes-kheyout, alleluia. Pai ow-ou fai afshop khen ni-ethowab tiro entaf.",
        "Alleluia, Alleluia, Alleluia.",
        "Esmo Efnouti khen ni-ethowab tiro entaf, alleluia.",
        "Esmo erof khen pi-tagro ente tef-gom, alleluia.",
        "Esmo erof e-ehri hijen tefmet-gowri, alleluia.",
        "Esmo erof kata ep-ashai ente tef-met-nishti, alleluia.",
        "Esmo erof khen ou-esmi ensalpen-ghos, alleluia.",
        "Esmo erof khen ou-epsal-terion nem ou-kithara, alleluia.",
        "Esmo erof khen han-kem-kem nem han-khoros, alleluia.",
        "Esmo erof khen han-kap nem ou-orghanon, alleluia.",
        "Esmo erof khen han-kim-valon ene-setou-esmi, alleluia.",
        "Esmo erof khen han-valon ente ou-eshlilowi, alleluia.",
        "Nifi niven maro-esmo tiro Ee-efran Emipshois Pennouti, alleluia.",
        "Zoxa Patree ke Eio ke Agio Epnevmati, alleluia.",
        "Ke neen ke a-ee ke estos e-onas ton e-onon amen. Alleluia.",
        "Alleluia, alleluia, Zoxa si o Theos emon, alleluia.",
        "Alleluia, alleluia, pi-ow-ou fa pennouti pe, alleluia."
      ],
      "arabic": [
        "الهوس الرابع",
        "(المزمور 148)",
        "+ سبحوا الرب من السموات هلليلويا. سبحوه في الأعالي. ",
        "سبحوه يا جميع ملائكته هلليلويا. سبحوه يا جميع جنوده.",
        "+ سبحيه أيتها الشمس والقمر هلليلويا. سبحيه يا جميع كواكب النور.",
        "سبحيه يا سماء السموات هلليلويا. ويا أيتها المياه التي فوق السموات. ",
        "+ لتسبح جميعها لإسم الرب هلليلويا. لأنه قال فكانت.",
        "وأمر فخلقت هلليلويا. أقامها إلى الأبد وإلى أبد الأبد. ",
        "+ وضع لها أمراً فلن تتجاوزه هلليلويا. سبحي الرب من الأرض.",
        "أيتها التنانين وجميع الأعماق هلليلويا. النار والبرد والثلج والجليد والريح العاصفة الصانعة كلمته. ",
        "+ الجبال العالية وجميع الآكام هلليلويا. الأشجار المثمره وكل الأرز.",
        "الوحوش وكل البهائم هلليلويا. الهوام وكل الطيور ذات الأجنحة.",
        "+ ملوك الأرض وكل الشعوب هلليلويا. الرؤساء وكل حكام الأرض.",
        "الشبان والعذارى هلليلويا. الشيوخ والصبيان.",
        "+ فليسبحوا جميعاً إسم الرب هلليلويا. لأنه قد تعالى إسمه وحده. ",
        "شكره كائن على الأرض وفي السماء هلليلويا. ويرفع قرن شعبه. ",
        "+ سُبحاً لجميع قديسيه هلليلويا. بني إسرائيل، الشعب القريب إليه. ",
        "(المزمور 149)",
        "هلليلويا، هلليلويا، هلليلويا. ",
        "إنشدوا للرب نشيداً جديداً هلليلويا. لأن تسبحته في بيعة القديسين.",
        "+ فليفرح إسرئيل بخالقه هلليلويا. وبنوا صهيون فليتهللوا بملكهم.",
        "فليسِّبحوا إسمه القدوس بصفِ هلليلويا. بدف ومزمار فليرتلوا له. ",
        "+ لأن الرب يُسر بشعبه هلليلويا. يعلي الودعاء بالخلاص. ",
        "يفتخر القديسون بمجد هلليلويا. ويتهللون على مضاجعهم.",
        "+ تعليات الله في حناجرهم هلليلويا. وسيوف ذات حدين في أيديهم. ",
        "ليصنعوا نقمة في الأمم هلليلويا. وتوبيخات في الشعوب. ",
        "+ ليوثقوا ملوكهم بقيود هلليلويا. وإشرافهم بأغلال للأيدي من حديد. ",
        "ليصنعوا بهم حُكماً مكتوباً هلليلويا. هذا المجد كائن في جميع قديسيه. ",
        "(المزمور 150)",
        "+ هلليلويا، هلليلويا، هلليلويا.",
        "+ سبحوا الله في جميع قديسيه هلليلويا. ",
        "سبحوه في جلد قوته هلليلويا.",
        "+ سبحوه على مقدرته هلليلويا. ",
        "سبحوه ككثرة عظمته هلليلويا.",
        "+ سبحوه بصوت البوق هلليلويا.",
        "سبحوه بالمزمار والقيثار هلليلويا.",
        "+ سبحوه بدفوف وصفوف هلليلويا.",
        "سبحوه بأوتار وأرغن هلليلويا.",
        "+ سبحوه بصنوج حسنة الصوت هلليلويا.",
        "سبحوه بصنوج التهليل هلليلويا.",
        "+ كل نسمة فلتسبح إسم الرب الهنا هلليلويا.",
        "المجد للآب والإبن والروح القدس هلليلويا.",
        "+ الآن وكل أوان وإلى دهر الدهور آمين هلليلويا. ",
        "هلليلويا، هلليلويا. المجد لك يا إلهنا هلليلويا.",
        "+ هلليلويا، هلليلويا. المجد لإلهنا هلليلويا. "
      ]
    }
  