export default {
    name:'Theotokia Parts 10 to 15',
    "coptic": [],
    "english": [
    "You are more worthy, than all of the saints, to ask on our behalf, O full of grace. ",
    "+ You are exalted, more than the patriarchs, and honored more, than the prophets. ",
    "And you have a seeking, more special, than the Cherubim, and the Seraphim. ",
    "+ For you are truly, the pride of our race, and the intercessor, of our souls. ",
    "Intercede for us, before our Savior, that He may keep us firm, in the upright faith. ",
    "+ That He may grant us, the forgiveness of our sins, in order to win mercy, through your intercessions. ",
    "The Eleventh Part:",
    "All the high names, of the incorporeal, thousands of angels, and archangels. ",
    "+ They did not attain, your high blessedness, O who is clothed in, the glory of the Lord of hosts. ",
    "You are more brighter, than the sun, and more sparkling, than the Cherubim. ",
    "+ And the Seraphim, with the six wings, which are joyfully, hovering over you. ",
    "The Twelfth Part:",
    "Your glory O Mary, is higher than the heaven, you are more honored than the earth, and its inhabitants. ",
    "+ For you are truly, the real path, leading up, to the heavens.",
    "You are clothed, with joy and gladness, and girdled with power, O daughter of Zion. ",
    "+ O who was clothed, with the garments of the heavenly, so that you covered Adam, with the garments of grace. ",
    "And restored him again, to the Paradise, the rejoicing place, and dwelling of the righteous.",
    "The Thirteenth Part: ",
    "+ A true tabernacle, is Mary the Virgin, placed in its midst, the true testimonies. ",
    "The undefiled ark, overlaid roundabout with gold, and the mercy seat, of the Cherubim. ",
    "+ The golden vessel, where the manna was hidden, behold the Word of the Father, came and took flesh from you. ",
    "The golden lampstand, carrying the true Light, who is the unapproachable, Light of the world.",
    "+ The golden censer, carrying the live coal, and the chosen incense, with a rich aroma. ",
    "The rod of Aaron, that blossomed, and the holy flower, of the incense.",
    "+ All these together, direct us to, the miraculous Birth, O Virgin Mary. ",
    "The Fourteenth Part: ",
    "You decorated our souls, O Moses the prophet, by the honor of the tabernacle, which you have adorned.",
    "+ The first tabernacle, which Moses had made, was the place of the forgiveness, for the children of Israel. ",
    "He made it with glory, as commanded by the Lord, and according to the patterns, shown unto him. ",
    "+ There was an ark, in the tabernacle, overlaid with gold, from within and without.",
    "There was a mercy seat, in the tabernacle, and the golden Cherubim, overshadowed it. ",
    "+ There was a golden pot, in the tabernacle, and a measure of the manna, was hidden in it. ",
    "There was a golden lampstand, in the tabernacle, and the seven lamps, shone upon it.",
    "+ There was a golden censer, in the tabernacle, and the chosen aloe, was in its midst.",
    "There was a flower of incense, in the tabernacle, inhaled by all, the house of Israel. ",
    "+ There was the rod of Aaron, in the tabernacle, this which has blossomed, without planting or watering. ",
    "There was a golden table, in the tabernacle, and the oblation bread, was placed upon it.",
    "+ There was a high priest, in the tabernacle, offering sacrifices, on account of the peoples sins.",
    "When the Pantocrator, smelled the aroma, He lifted up the sins, of the people.",
    "+ Through Mary, the daughter of Joachim, we learned of the true Sacrifice, for the forgiveness of sin.",
    "The Fifteenth Part:",
    "Who can speak of, the honor of the tabernacle, which was decorated, by the prophet.",
    "+ When the chosen scholars, of the holy books, saw it, they were greatly amazed.",
    "They thought, with their bright minds, and explained it, through the holy books.",
    "+ They called Mary, the daughter of Joachim, the true tabernacle, of the Lord of hosts.",
    "They likened the ark, to the Virgin, and its chosen gold, to her purity.",
    "+ They likened the mercy seat, to the Virgin, and the Cherubim of glory, overshadowing her.",
    "They likened the golden pot, to the Virgin, and the measure of the manna, to our Savior.",
    "+ They likened the golden candlestand, to the Church, and the seven lamps, to its seven orders. ",
    "They likened the golden censer, to the Virgin, and its aloes, to Emmanuel.",
    "+ They likened the flower of incense, to Mary the Queen, and the chosen incense, to her virginity. ",
    "They likened the rod of Aaron, to the wood of the Cross, which my Lord was crucified upon, in order to save us.",
    "+ They likened the golden table, to the altar, and the oblation bread, to the Body of the Lord. ",
    "They likened the high priest, to our Savior, the true Sacrifice, for the forgiveness of sins. ",
    "+ He who offered Himself, as an acceptable sacrifice, upon the Cross, for the salvation of our race. ",
    "His good Father, smelled Him, in the evening, on Golgotha. ",
    "+ He opened the gate, of Paradise, and restored Adam again, to his authority. ",
    "Through Mary, the daughter of Joachim, we learned of the true Sacrifice, for the forgiveness of sins.",
    "+ And we too, hope to win mercy, through your intercessions, with the Lover of Mankind. "
    ],
    "copticEnglish": [
    "Teoi enhe-kanos, e-hote ni-ethowab tiro, ethre-tovh e-gon, o thie-ethmen-ehmot.",
    "Tit-shosi e-mashow, e-hote ni-patriarshis, owoh te-tai-yoot, ehote ni-eprofitis.",
    "O-on to jin-moshi, khen ou-par-riseia, e-hote ni-Sherobim, nem ni-Seraphim.",
    "Entho ghar alithos, pep-sho-sho empen genos, owoh ti-epros-tatis, ente nen epsishi.",
    "Arip-resvevin e-gon, nahren pen-sotir, hopos entef tagron, khen pi-nahti etsoton.",
    "Entef-er-ehmot nan, empi-ko evol ente nennovi, enten shashni evnai, hetinip-resveia.",
    " Eleventh Part:",
    "Ran niven etit-shosi, ente-ni-asomatos, ni-ananshon-angelos, nem arshi-angelos.",
    "Empo eshfo epet-chisi, ente ne-makaris-mos, o-thiet-gloh empi-o-o, ente Epshois sava-ot.",
    "Ti-heiak-ten evol, e-hote efri, teoi enlam-epros, e-hote ni-Sherobim.",
    "Nem ni-Seraphim, na pi-so-oo entenh, se-er-ripi-zin khago, khen o-eshli-lowe.",
    "Twelfth Part:",
    "Pe-o-o Maria, chosi e-hote etfe, te-tayot epkahi, nem ni-etshop en-khitf.",
    "Entho ghar alithos, te ti-setrata emmi, etoi emmam-moshi, e-epshoi enni-fe-owe.",
    "Areti heyoti, emif-rashi nem ep-thelil, ari-morti en-ogom, o etsheri en-Sion.",
    "O thi-e-tas ti-heyots, ente-hebso enna ni-fe-owe, sha-entes-hobs en-Adam, en-et-hebso empi-ehmot.",
    "Ari-tastof en-kesop, e-pi parazisos, epto-pos emip-onof, efma en-shopi en nizikeos.",
    "Thirteenth Part:",
    "O-eskini emmi, te Maria ti-Parthenos, evki khen tes-miti, enje ni-met-methrev e-ten-hoot.",
    "Ti-kivotos en-at-tholeb, et-oshg ennoub ensasa niven, nem pi-eilas-tirion, en-Sherobim ekon.",
    "Pistamnos ennoub, e-re pi-manna hip enkhitf, yes pi-Logos ente Efiot, e-afit-she-sarex enkhiti.",
    "Ti-likh-nia ennoub, etfai khah pi-ou-oyni emmi, ete ef-ou-oyni empi-kosmos, pi-atish-khownt e-rof.",
    "Ti-shouri ennoub, etfai kha pi-jebs en-ekrom, nem pi-estoy-noufi et-sotp, en-aromata.",
    "Pi-eshvot ente A-aron, e-taf firi evol, nem ti-ehriri ethowab, ente pistoi-noufi.",
    "Nai tiro evsop, se-ersim-menin nan, mpe-jin-misi enishfiri, O Maria ti-Parthenos.",
    "Fourteenth Part:",
    "Aksol-sel ennen-epsishi, o Moysis piprophitis, khen ep-taio en-ti-eskini, e-tak-sel-sols evol.",
    "Ti-eskini enhowe-ti, e-ta Moysis thamios, en-ouman-ka-novi evol, ente nen-shiri empis-rael.",
    "Af-thamios khen ou-o-ou, katap-saji emip-shoise, nem kata ni-tipos tiro, e-tav-tamof ero-ou.",
    "Ou-on ou-kivotos, ki khen ti-eskini, esla-leyoot ennoub, sakhoun nem savol.",
    "Ou-on ou-eilas-tireion, ki khen ti-eskini, han Sherobim ennoub, se-er-khibi e-gof.",
    "Ou-on ou-estam-nos ennoub, ki khen ti-eskini, e-re oushi-em-manna hip, enikhri enkhitf.",
    "Ou-on ou-likhnia ennoub, ki khen ti-eskini, e-re pi-shashf enkhibs, er-ou-oyni eigos.",
    "Ou-on ou-shouri ennoub, ki khen ti-eskini, e-re pi-kina-mownon, et-sotp khen tes-meti.",
    "Ou-on ou-ehriri enestoi-noufi, ki khen ti-eskini, evshow-lem e-ros tiro, enje na ep-e empis-rael.",
    "Ou-on ou-eshvowt ente A-aron, ki khen ti-eskini, fai-e-taf-viri evol, khowris cho nem etso.",
    "Ou-on ou-etra-peza ennoub, ki khen ti-eskini, ep-owik enti-epro-tesis, ki e-ehri e-gos.",
    "Ou-on ou-arshi-erevs, ki khen ti-eskini, Ef-en-shosho-oushi e-epshowi, ejen ni-novi ente pi-laos.",
    "Afshan showlem e-rof, enje pi-Pantocrator, shaf-owli emmav, enni-novi ente pi-laos.",
    "Evol hiten Maria, etshiri en-Yowakim, an-sou-en pi-shou-show-oushi emmi, anka novi evol.",
    "Fifteenth Part:",
    "Nim pethna esh-saji, em-ep-taio enti-eskini, e-taf-sel-sowls evol, enje piprophitis.",
    "Eitav-nav eiros, enje ni-sowtp ensakh, ente ni-eghrafi ethowab, afitch esh-firi e-mashow.",
    "Avmok-mek evol, khen poukati et-shom, af-ermine-vin emmos, khen ni-eghrafi ethowab.",
    "Avmouti e-Maria, etshiri en-Yowakim, je ti-eskini emmi,\nente Epshoise sava-owt.",
    "Aven ti-kivotos, hijen ti-Parthenos, pes-kenoub et-sotp, hijen pes-touvo.",
    "Aven pi-e-lastirion, hijen ti-Parthenos, yes ni-Sherobim ente ep-ow-ou, se-er-khibi egows.",
    "Aven pistamnos ennoub, hijen ti-Parthenos, pef-keshi em-manna, hijen pen-Sotir.",
    "Aven ti-likh-nia ennoub, hijen ti-eklisia, peske shashf enkhibs, hijen pi-shashf en-taghma.",
    "Aven ti-shouri ennoub, hijen ti-Parthenos, pes-ki-na-mownon,\nhijen Emmano-eel.",
    "Aven ti-ehriri enistoi-noufi, hijen Maria ti-owro, pes-kestoi-noufi et-sotp, hijen tes-parthenia.",
    "Aven pi-eshvot ente A-aron, hijen epshe etne pis-tavros, etav-esh pashois e-rof, sha entef sowti emmon.",
    "Av-en titra-peza ennoub, hijen pima-en-ershow-oushi, ep-oyk enti-epro-tesis, hijen ep-sowma emip-shois.",
    "Av-en pi-arshi-eirevs, hijen pen-Sotir, pi-shosho-oushi emmi, enka novi evol.",
    "Fai e-taf-enf e-epshowi, enou-thisia es-ship, hijen pis-tavros, kha ep-ougai em-pengenos.",
    "Afshow-lem erof, enje Pefiout en-aghathos, em-evnav ente han-arouhi, hijen ti-ghol-ghotha.",
    "Af-ou-own emif-ro, em-pi-parazisos, aftas-to en-Adam, etef-arshi enke-sop.",
    "Evol hiten Maria, et-shiri en-Yowakim, an-sou-en pi-shosho-oushi, enka novi evol.",
    "Anon hon ten-tovh, ethren shashni evnai, hiten ni-epres-via, en-totof empi-mairowmi."
    ],
    "arabic": [
    "القطعة العاشرة - تي اوي إنهيكانوس",
    "أنتِ مستحقة، أكثر من جميع القديسين، أن تطلبي عنا، أيتها الممتلئة نعمة. ",
    "+ أنتِ مرتفعة جداً، أكثر من رؤساء الآباء، ومكرمة أفضل، من الأنبياء. ",
    "ولك سعيً، بدالة، أكثر من الشاروبيم، والسيرافيم. ",
    "+ لأنكِ أنتِ بالحقيقة، فخر جنسنا، وشفيعة، نفوسنا. ",
    "إشفعي فينا، أمام مخلصنا، لكي يثبتنا، في الإيمان المستقيم. ",
    "+ وينعم لنا، بمغفرة خطايانا، لنفوز برحمةٍ، بشفاعاتِك. ",
    "القطعة الحادية عشر:",
    "كل الأسماء العالية، التي لغير المتجسدين، ألوف الملائكة، ورؤساء الملائكة. ",
    "+ لم يبلغوا، عظمة طوباوياتِك، أيتها المشتملة، بمجد رب الجنود. ",
    "أنتِ مضيئة، أكثر من الشمس، ولامعة أكثر، من الشاروبيم. ",
    "+ والسيرافيم، ذوى الستة الأجنحة، يرفرف عليكِ، بتهليل. ",
    "القطعة الثانية عشر: ",
    "مجدِك يا مريم، أرفع من السماء، وأنت أكرم من الأرض، وسكانها. ",
    "+ لأنكِ أنتِ بالحقيقة، الطريق الحقيقي، المؤدي، إلى السموات. ",
    "لبسِت الفرح، والتهليل، وتمنطقتِ بالقوة، يا إبنة صهيون. ",
    "+ يا مَنْ لبسِت، لباس السمائيين، حتى سترتِ آدم، بلباس النعمة. ",
    "ورددته مرة أخري، إلى الفردوس، موضع الفرح، ومسكن الصديقين. ",
    "القطعة الثالثة عشر: ",
    "+ قبة حقيقية، هي مريم العذراء، موضوع في وسطها، الشهادات الصادقة. ",
    "التابوت الغير الدنس، المصَّفح بالذهب، من كل ناحية، والغطاء الكاروبي. ",
    "+ القسط الذهبي، المخفي فيه المَنَّ، هوذا كلمة الآب، أتى وتجسد منكِ. ",
    "المنارة الذهبية، الحاملة النور الحقيقي، الذي هو نور العالم، الذي لا يُدنى منه. ",
    "+ المجمرة الذهبية، الحاملة جمر النار، والبخور المختار، العنبري. ",
    "عصا هارون، التي أزهرت، والزهرة المقدسة، التي للبخور. ",
    "+ هذة جميعها معاً، تدُلنا على، ولادتك العجيبة، يا مريم العذراء. ",
    "القطعة الرابعة عشر: ",
    "زينت نفوسنا، يا موسى النبي، بكرامة القبة، التي زينتها. ",
    "+ القبه الأولى، التي صنعها موسى، موضع مغفرة خطايا، بني إسرائيل. ",
    "صنعها بمجد، كقول الرب، وكجميع المُثل، التي أعلمه بها. ",
    "+ كان في القبة، تابوت مصَّفح، بالذهب من داخل، ومن خارج. ",
    "كان في القبة، غطاء وكاروبا، ذهب، يظللان عليه. ",
    "+ كان في القبة، قسط ذهبي، وكيل مَنَّ، مخفي فيه. ",
    "كان في القبة، منارة من ذهب، وسبعة سُرج، تضئ عليها. ",
    "+ كان في القبة، مجمرة من ذهب، والعود المختار، في وسطها. ",
    "كان في القبة، زهرة بخور، يستنشق رائحتها، جميع آل بيت إسرائيل. ",
    "+ كان في القبة، عصا هرون، هذه التي أزهرت، بغير غرس ولا سقي. ",
    "كان في القبة، مائدة ذهبية، وخبز التقدمة، موضوعاً عليها.",
    "+ كان في القبة، رئيس كهنة، يُصعد الذبائح، عن خطايا الشعب.",
    "إذا إشتم رائحتها، ضابط الكل، يرفع هنالك، خطايا الشعب.",
    "+ من قِبَل مريم، إبنة يواقيم، عرفنا الذبيحة الحقيقية، لمغفرة الخطايا.",
    "القطعة الخامسة عشر:",
    "من يقدر أن، يصف كرامة، القبة التي، زينها النبي.",
    "+ لما رآها، المعلمون المختارون، للكتب المقدسة، تعجبوا جداً.",
    "وفكروا، بفهمهم السامي، وفسَّروها، من الكتب المقدسة.",
    "+ ودعوا مريم، إبنة يواقيم، القبة الحقيقية، التي لرب الجنود.",
    "شبهوا التابوت، بالعذراء، وذهبه المختار، بطهارتها.",
    "+ شبهوا الغطاء، بالعذراء، وكاروبا المجد، يظللان عليها.",
    "شبهوا القسط الذهبي، بالعذراء، وكيلة المَنَّ، بمخلصنا. ",
    "+ شبهوا المنارة الذهبية، بالكنيسة، وسُرجها السبعة، بالسبع طغمات. ",
    "شبهوا المجمرة الذهبية، بالعذراء، وعنبرها، بعمانوئيل. ",
    "+ شبهوا زهرة البخور، بمريم الملكة، وبخورها المختار، ببتوليتها. ",
    "شبهوا عصا هرون، بخشبة الصليب، التي صُلب ربي عليها، حتى خلصنا. ",
    "+ شبهوا المائدة الذهبية، بالمذبح، وخبز التقدمة، بجسد الرب. ",
    "شبهوا رئيس الكهنة، بمخلصنا، الذبيحة الحقيقية، لمغفرة الخطايا. ",
    "+ هذا الذي أصعد ذاته، ذبيحة مقبولة، على الصليب، عن خلاص جنسنا. ",
    "فإشتمه، أبوه الصالح، وقت المساء، على الجلجثة. ",
    "+ فتح باب الفردوس، وردَّ آدم، إلى رئاسته، مرة أخرى. ",
    "من قِبَل مريم، إبنة يواقيم، عرفنا الذبيحة الحقيقية، لمغفرة الخطايا. ",
    "+ ونحن أيضاً، نطلب أن نفوز برحمةٍ، بشفاعاتِك، عند محب البشر. "
    ]
    }