export default {
    name: "Third Hoos",
      "coptic": [
        "Pihwc `mMahsomt",
        "`K`cmarwout `P[oic `Vnou] `nte nenio]@ `kerhou`o `cmarwout `kerhou`o [ici sa ni`eneh. ",
        "+ `F`cmarwout `nje piran e;ouab `nte pek`[email&#160;protected] `ferhou`o `cmarwout `ferhou`o [ici sa ni`eneh. ",
        "`K`cmarwout qen piervei `nte pek`wou e;[email&#160;protected] `kerhou`o `cmarwout `kerhou`o [ici sa ni`eneh. ",
        "+ `K`cmarwout vye;nau `eninoun efhemci hijen Ni,[email&#160;protected] `kerhou`o `cmarwout `kerhou`o [ici sa ni`eneh.",
        "`K`cmarwout hijen pi`;ronoc `nte [email&#160;protected] `kerhou`o `cmarwout `kerhou`o [ici sa ni`eneh.",
        "+ `K`cmarwout qen pi`ctere`wma `nte `[email&#160;protected] `kerhou`o `cmarwout `kerhou`o [ici sa ni`eneh.",
        "`Cmou `e`P[oic ni`hbyou`i tyrou `nte `P[[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic nivyou`[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic niaggeloc tyrou `nte `P[[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic nimwou tyrou etca `pswi `n`[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic nijom tyrou `nte `P[[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic piry nem [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic niciou tyrou `nte `[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic nimounhwou nem niiw]@ hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic ni[ypi nem ni;[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic ni`pneuma [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic pi`,rwm nem [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic pi`wjeb nem [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic niiw] nem [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic ni`ejwrh nem ni`[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic piouwini nem pi,[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic pijaf nem pi`[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic ]pa,ny nem pi,[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic nicetebryj nem ni[[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic pikahi [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic nitwou nem nikalamvwou [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic ny tyrou etryt hijen `pho `m`[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic ni`amaiou nem [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic nikytoc nem en,ai niben etkim qen [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic nihala] tyrou `nte `[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic ni;yrion nem nitebnwou`i [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh. ",
        "`Cmou `e`P[oic nisyri `nte [email&#160;protected] ouwst `m`P[[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic niouyb `nte `P[[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic ni`ebiaik `nte `P[[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic ni`pneuma nem ni'u,y `nte ni`;[email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic nye;ouab nem nyet;ebiyout qen [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "`Cmou `e`P[oic `Ananiac `Azariac Micayl ke [email&#160;protected] hwc `erof `arihou`o [acf sa ni`eneh.",
        "+ `Cmou `e`P[oic nyetercebec;e `m`P[oic `Vnou] `nte nenio]@ hwc `erof `arihou`o [acf sa ni`eneh."
      ],
      "english": [
        "Blessed are You O Lord God of our fathers, and exceedingly to be blessed and exalted above all forever.",
        "+ Blessed is Your holy name and Your glory, and exceedingly to be blessed and exalted above all forever.",
        "Blessed are You in the holy temple of Your glory, and exceedingly to be blessed and exalted above all forever.",
        "+ Blessed are You who beholds the depths and sits upon the Cherubim, and exceedingly to be blessed and exalted above all forever.",
        "Blessed are You on the throne of Your kingdom, and exceedingly to be blessed and exalted above all forever.",
        "+ Blessed are You in the firmament of heaven, and exceedingly to be blessed and exalted above all forever. ",
        "Bless the Lord O you works of the Lord, praise Him and exalt Him above all forever. ",
        "+ Bless the Lord O heaven, praise Him and exalt Him above all forever. ",
        "Bless the Lord all you angels of the Lord, praise Him and exalt Him above all forever.",
        "+ Bless the Lord all you waters above the heaven, praise Him and exalt Him above all forever.",
        "Bless the Lord all you powers of the Lord, praise Him and exalt Him above all forever.",
        "+ Bless the Lord O sun and moon, praise Him and exalt Him above all forever.",
        "Bless the Lord all you stars of heaven, praise Him and exalt Him above all forever.",
        "+ Bless the Lord O you rain and dew, praise Him and exalt Him above all forever.",
        "Bless the Lord O you clouds and winds, praise Him and exalt Him above all forever.",
        "+ Bless the Lord all you spirits, praise Him and exalt Him above all forever.",
        "Bless the Lord O fire and heat, praise Him and exalt Him above all forever.",
        "+ Bless the Lord O cold and heat, praise Him and exalt Him above all forever.",
        "Bless the Lord O you dew and winds, praise Him and exalt Him above all forever.",
        "+ Bless the Lord O you nights and days, praise Him and exalt Him above all forever.",
        "Bless the Lord O light and darkness, praise Him and exalt Him above all forever. ",
        "+ Bless the Lord O frost and cold, praise Him and exalt Him above all forever.",
        "Bless the Lord O snow and ice, praise Him and exalt Him above all forever.",
        "+ Bless the Lord O you lightnings and clouds, praise Him and exalt Him above all forever.",
        "Bless the Lord all the earth, praise Him and exalt Him above all forever.",
        "+ Bless the Lord O you mountains and all hills, praise Him and exalt Him above all forever.",
        "Bless the Lord all you things that spring up on the earth, praise Him and exalt Him above all forever.",
        "+ Bless the Lord O you fountains, praise Him and exalt Him above all forever.",
        "Bless the Lord O you seas and rivers, praise Him and exalt Him above all forever.",
        "+ Bless the Lord O you whales and all that moves in the waters, praise Him and exalt Him above all forever.",
        "Bless the Lord all you birds of the sky, praise Him and exalt Him above all forever.",
        "+ Bless the Lord all you wild beasts and cattle, praise Him and exalt Him above all forever.",
        "Bless the Lord O you sons of men, worship the Lord, praise Him and exalt Him above all forever.",
        "+ Bless the Lord O Israel, praise Him and exalt Him above all forever.",
        "Bless the Lord O you priests of the Lord, praise Him and exalt Him above all forever.",
        "+ Bless the Lord O you servants of the Lord, praise Him and exalt Him above all forever.",
        "Bless the Lord O you spirits and souls of the just, praise Him and exalt Him above all forever.",
        "+ Bless the Lord O you holy and humble of heart, praise Him and exalt Him above all forever.",
        "Bless the Lord O Hananiah Azariah Mishael and Daniel, praise Him and exalt Him above all forever. ",
        "+ Bless the Lord O you who worship the Lord the God of our fathers, praise Him and exalt Him above all \nforever. "
      ],
      "copticEnglish": [
        "Ek-esmaro-ot Epshois Efnuoti ente nenyoti, ek-erho-ou esmaro-oot, ek-erho-ou chisi sha ni-eneh.",
        "Ef-esmaro-oot enje piran ethowab ente pek-ow-ou, ek-erho-ou esmaro-oot, ek-erho-ou chisi sha ni-eneh.",
        "Ek-esmao-oot khen pi-erfei ente pek-o-ou ethowab, ek-erho-ou esmaro-oot, ek-erho-ou chisi shani eneh.",
        "Ek-esmaro-oot feieth-nav eine-noun ef-hemsi hijen ni-Sherobim, ek-erho-ou esmaro-oot, ek-erho-ou chisi sha ni-eneh.",
        "Ek-esmaro-oot hijen pi-ethronous ente tek-met-oro, ek-erho-ou esmaro-oot, ek-erho-ou chisi sha ni-eneh.",
        "Ek-esmaro-oot khen pis-tre-oma ente etfe, ek-erho-ou esmaro-oot, ek-erho-ou chisi sha ni-eneh.",
        "Esmo Epshois, ni-ehvi-owi tiro ente Epshois, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-fee-owi, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-angelos tiro ente Epshois, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, no-mo-ou tiro etsa epshoi enetfe, hos erof ari-ho-oo chasf sha ni-eneh. ",
        "Esmo Epshois, nigom tiro ente Epshois, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, piri nem peyoh, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-seyo tiro ente etfe, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-mon-ho-ou nem nieyoti, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-et-shipi nem ni-thio, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-epnevma tiro, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, pi-ekrom nem pi-qavma, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, pi-ojeb nem pi-kavson, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, niyouti nem ni-nifi, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-egorh nem ni-e-ho-ou, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, pi-o-oyni nem pi-qaki, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, pigaf nem pi-o-jeb, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ti-pakhni nem pi-sheyon, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, nisitev-rig nem nit-shipi, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, pi-kahi tirf, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, nito-ou nem ni-kalam-fo-ou-tiro, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-tiro etrit hijen ep-ho emip-kahi, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-mo-mi, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-amayo nem ni-yaro-ou, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-kitos nem enkai niven etkim khen nimo-ou, hos erof ari-ho-oo chasf sha ni-eneh. ",
        "Esmo Epshois, ni-halati tiro ente etfe, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-thereion nem ni-tev-ni-owi tiro, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-shiri ente. ni-romi ou-osht Emip-shois, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, pis-rael, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-oweep ente Epshois, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-eivi-ike ente Epshois, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-epnevma nem ni-epsishi ente ni-ethmi, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epchois, ni-ethowab nem ni-et-theveyot khen pouheet, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Coptic-English:\nEsmo Epshois, Ananeias, Azareias, Misaeil ke Daneiel, hos erof ari-ho-oo chasf sha ni-eneh.",
        "Esmo Epshois, ni-etir-se-veste Emipshois ente nenyoti, hos erof ari-ho-oo chasf sha ni-eneh.\n"
      ],
      "arabic": [
        "الهوس الثالث",
        "مبارك أنت أيها الرب إله أبائنا، ومتزايد بركة ومتزايد علواً إلى الآباد.",
        "+ مبارك إسم مجدك القدوس، ومتزايد بركة ومتزايد علواً إلى الآباد.",
        "مبارك أنت في هيكل مجدك المقدس، ومتزايد بركة ومتزايد علواً إلى الآباد.",
        "+ مبارك أنت أيها الناظر إلى الأعماق الجالس على الشاروبيم، ومتزايد بركة ومتزايد علواً إلى الآباد. ",
        "مبارك أنت على عرش مُلكك، ومتزايد بركة ومتزايد علواً إلى الآباد.",
        "+ مبارك أنت في فلك السماء، ومتزايد بركة ومتزايد علواً إلى الآباد.",
        "باركي الرب يا جميع أعمال الرب، سبحيه وزيديه علواً إلى الآباد.",
        "+ باركي الرب أيتها السموات، سبحيه وزيديه علواً إلى الآباد.",
        "باركوا الرب يا جميع ملائكة الرب، سبحوه وزيدوه علواً إلى الآباد.",
        "+ باركي الرب يا جميع المياه التي فوق السماء، سبحيه وزيديه علواً إلى الآباد.",
        "باركي الرب يا جميع قوات الرب، سبحيه وزيديه علواً إلى الآباد.",
        "+ باركا الرب أيتها الشمس والقمر، سبحاه وزيداه علواً إلى الآباد. ",
        "باركي الرب يا سائر نجوم السماء، سبحيه وزيديه علواً إلى الآباد. ",
        "+ باركي الرب أيتها الأمطار مع الأنداء، سبحيه وزيديه علواً إلى الآباد.",
        "باركي الرب أيتها السُحب والرياح، سبحيه وزيديه علواً إلى الآباد.",
        "+ باركي الرب يا جميع الأرواح، سبحيه وزيديه علواً إلى الآباد.",
        "باركا الرب أيتها النار والحرارة، سبحاه وزيداه علواً إلى الآباد.",
        "+ باركا الرب أيها البرد والحر، سبحاه وزيداه علواً إلى الآباد.",
        "باركي الرب أيتها الأهوية والأنداء، سبحيه وزيديه علواً إلى الآباد.",
        "+ باركي الرب أيتها الليالي والأيام، سبحيه وزيديه علواً إلى الآباد.",
        "باركا الرب أيها النور والظلمة، سبحاه وزيداه علواً إلى الآباد. ",
        "+ باركا الرب أيها البرد والصقيع، سبحاه وزيداه علواً إلى الآباد.",
        "باركا الرب أيها الجليد والثلج، سبحاه وزيداه علواً إلى الآباد. ",
        "+ باركي الرب أيتها البروق والسحب، سبحيه وزيديه علواً إلى الآباد. ",
        "باركي الرب أيتها الأرض كلها، سبحيه وزيديه علواً إلى الآباد.",
        "+ باركي الرب أيتها الجبال وجميع الآكام، سبحيه وزيديه علواً إلى الآباد.",
        "بارك الرب يا جميع ما يَنبت على وجه الأرض، سبحه وزده علواً إلى الآباد.",
        "+ باركي الرب أيتها الينابيع، سبحيه وزيديه علواً إلى الآباد.",
        "باركي الرب أيتها البحار والأنهار، سبحيه وزيديه علواً إلى الآباد.",
        "+ باركي الرب أيتها الحيتان وجميع ما يتحرك في الماء، سبحيه وزيديه علواً إلى الآباد.",
        "باركي الرب يا جميع طيور السماء، سبحيه وزيديه علواً إلى الآباد.",
        "+ باركي الرب أيتها الوحوش وكل البهائم، سبحيه وزيديه علواً إلى الآباد.",
        "باركوا الرب يا بني البشر، وأُسجدوا للرب، سبحوه وزيدوه علواً إلى الآباد.",
        "+ بارك الرب يا إسرائيل، سبحه وزده علواً إلى الآباد. ",
        "باركوا الرب يا كهنة الرب، سبحوه وزيدوه علواً إلى الآباد.",
        "+ باركوا الرب يا عبيد الرب، سبحوه وزيدوه علواً إلى الآباد.",
        "باركوا الرب يا أرواح وأنفس الصديقين، سبحوه وزيدوه علواً إلى الآباد.",
        "+ باركوا الرب أيها القديسون والمتواضعو القلوب، سبحوه وزيدوه علواً إلى الآباد.",
        "باركوا الرب يا حنانيا وعزاريا وميصائيل ودانيال، سبحوه وزيدوه علواً إلى الآباد. ",
        "+ باركوا الرب يا عابدي الرب إله أبائنا، سبحوه وزيدوه علواً إلى الآباد."
      ]
    }
  